/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppCamerasRouteImport } from './routes/_app/cameras'
import { Route as AppCameraCameraIdRouteImport } from './routes/_app/camera.$cameraId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCamerasRoute = AppCamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => AppRoute,
} as any)
const AppCameraCameraIdRoute = AppCameraCameraIdRouteImport.update({
  id: '/camera/$cameraId',
  path: '/camera/$cameraId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/cameras': typeof AppCamerasRoute
  '/camera/$cameraId': typeof AppCameraCameraIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/cameras': typeof AppCamerasRoute
  '/camera/$cameraId': typeof AppCameraCameraIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/cameras': typeof AppCamerasRoute
  '/_app/camera/$cameraId': typeof AppCameraCameraIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/admin' | '/cameras' | '/camera/$cameraId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/admin' | '/cameras' | '/camera/$cameraId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/cameras'
    | '/_app/camera/$cameraId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cameras': {
      id: '/_app/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof AppCamerasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/camera/$cameraId': {
      id: '/_app/camera/$cameraId'
      path: '/camera/$cameraId'
      fullPath: '/camera/$cameraId'
      preLoaderRoute: typeof AppCameraCameraIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCamerasRoute: typeof AppCamerasRoute
  AppCameraCameraIdRoute: typeof AppCameraCameraIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCamerasRoute: AppCamerasRoute,
  AppCameraCameraIdRoute: AppCameraCameraIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
