/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppBridgesRouteImport } from './routes/_app/bridges'
import { Route as AppCamerasRouteImport } from './routes/_app/cameras'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as UkIndexRouteImport } from './routes/uk/index'
import { Route as UkContactRouteImport } from './routes/uk/contact'
import { Route as UkFaqRouteImport } from './routes/uk/faq'
import { Route as UkHowItWorksRouteImport } from './routes/uk/how-it-works'
import { Route as AppCameraCameraIdRouteImport } from './routes/_app/camera.$cameraId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppBridgesRoute = AppBridgesRouteImport.update({
  id: '/bridges',
  path: '/bridges',
  getParentRoute: () => AppRoute,
} as any)
const AppCamerasRoute = AppCamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const UkIndexRoute = UkIndexRouteImport.update({
  id: '/uk/',
  path: '/uk/',
  getParentRoute: () => rootRouteImport,
} as any)
const UkContactRoute = UkContactRouteImport.update({
  id: '/uk/contact',
  path: '/uk/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const UkFaqRoute = UkFaqRouteImport.update({
  id: '/uk/faq',
  path: '/uk/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const UkHowItWorksRoute = UkHowItWorksRouteImport.update({
  id: '/uk/how-it-works',
  path: '/uk/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCameraCameraIdRoute = AppCameraCameraIdRouteImport.update({
  id: '/camera/$cameraId',
  path: '/camera/$cameraId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AppAdminRoute
  '/bridges': typeof AppBridgesRoute
  '/cameras': typeof AppCamerasRoute
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRoute
  '/uk/contact': typeof UkContactRoute
  '/uk/faq': typeof UkFaqRoute
  '/uk/how-it-works': typeof UkHowItWorksRoute
  '/uk/': typeof UkIndexRoute
  '/camera/$cameraId': typeof AppCameraCameraIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AppAdminRoute
  '/bridges': typeof AppBridgesRoute
  '/cameras': typeof AppCamerasRoute
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRoute
  '/uk/contact': typeof UkContactRoute
  '/uk/faq': typeof UkFaqRoute
  '/uk/how-it-works': typeof UkHowItWorksRoute
  '/uk': typeof UkIndexRoute
  '/camera/$cameraId': typeof AppCameraCameraIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/bridges': typeof AppBridgesRoute
  '/_app/cameras': typeof AppCamerasRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/profile': typeof AppProfileRoute
  '/uk/contact': typeof UkContactRoute
  '/uk/faq': typeof UkFaqRoute
  '/uk/how-it-works': typeof UkHowItWorksRoute
  '/uk/': typeof UkIndexRoute
  '/_app/camera/$cameraId': typeof AppCameraCameraIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/admin'
    | '/bridges'
    | '/cameras'
    | '/home'
    | '/profile'
    | '/uk/contact'
    | '/uk/faq'
    | '/uk/how-it-works'
    | '/uk/'
    | '/camera/$cameraId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/admin'
    | '/bridges'
    | '/cameras'
    | '/home'
    | '/profile'
    | '/uk/contact'
    | '/uk/faq'
    | '/uk/how-it-works'
    | '/uk'
    | '/camera/$cameraId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/_app/admin'
    | '/_app/bridges'
    | '/_app/cameras'
    | '/_app/home'
    | '/_app/profile'
    | '/uk/contact'
    | '/uk/faq'
    | '/uk/how-it-works'
    | '/uk/'
    | '/_app/camera/$cameraId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  UkContactRoute: typeof UkContactRoute
  UkFaqRoute: typeof UkFaqRoute
  UkHowItWorksRoute: typeof UkHowItWorksRoute
  UkIndexRoute: typeof UkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bridges': {
      id: '/_app/bridges'
      path: '/bridges'
      fullPath: '/bridges'
      preLoaderRoute: typeof AppBridgesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cameras': {
      id: '/_app/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof AppCamerasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/uk/': {
      id: '/uk/'
      path: '/uk'
      fullPath: '/uk/'
      preLoaderRoute: typeof UkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uk/contact': {
      id: '/uk/contact'
      path: '/uk/contact'
      fullPath: '/uk/contact'
      preLoaderRoute: typeof UkContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uk/faq': {
      id: '/uk/faq'
      path: '/uk/faq'
      fullPath: '/uk/faq'
      preLoaderRoute: typeof UkFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uk/how-it-works': {
      id: '/uk/how-it-works'
      path: '/uk/how-it-works'
      fullPath: '/uk/how-it-works'
      preLoaderRoute: typeof UkHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/camera/$cameraId': {
      id: '/_app/camera/$cameraId'
      path: '/camera/$cameraId'
      fullPath: '/camera/$cameraId'
      preLoaderRoute: typeof AppCameraCameraIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBridgesRoute: typeof AppBridgesRoute
  AppCamerasRoute: typeof AppCamerasRoute
  AppHomeRoute: typeof AppHomeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppCameraCameraIdRoute: typeof AppCameraCameraIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBridgesRoute: AppBridgesRoute,
  AppCamerasRoute: AppCamerasRoute,
  AppHomeRoute: AppHomeRoute,
  AppProfileRoute: AppProfileRoute,
  AppCameraCameraIdRoute: AppCameraCameraIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  UkContactRoute: UkContactRoute,
  UkFaqRoute: UkFaqRoute,
  UkHowItWorksRoute: UkHowItWorksRoute,
  UkIndexRoute: UkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
